#!/usr/bin/env python3
from __future__ import annotations

import argparse
import math
import random
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

EPSILON_STEP = 0.1
EPSILON_STEP_COUNT = 50
PECTIN_SIGMA = 1.0

EPSILON_RANGE_BY_TYPE = {
    "PR": (0.1, 2.0),
    "P": (2.1, 4.0),
    "PC": (4.1, 5.0),
}

CORE_ATOMTYPES = (
    ("C", 100.0, 2.673, 1.0),
    ("X", 50.0, 1.5, 1.0),
)

CORE_NONBOND_PARAMS = (
    ("C", "C", 1, 2.673000, 2.500000),
    ("C", "X", 1, 2.086500, 25.000000),
    ("X", "X", 1, 1.500000, 2.500000),
)


Assignment = Dict[str, float | int | str]
AssignmentMap = Dict[int, Dict[int, Assignment]]


def epsilon_step_values() -> List[float]:
    return [round(step * EPSILON_STEP, 1) for step in range(1, EPSILON_STEP_COUNT + 1)]


def epsilon_to_step_index(epsilon: float) -> int:
    return int(round(epsilon / EPSILON_STEP))


def step_index_to_epsilon(step_index: int) -> float:
    return round(step_index * EPSILON_STEP, 1)


def classify_pectin_epsilon(epsilon: float) -> str:
    if EPSILON_RANGE_BY_TYPE["PR"][0] <= epsilon <= EPSILON_RANGE_BY_TYPE["PR"][1]:
        return "PR"
    if EPSILON_RANGE_BY_TYPE["P"][0] <= epsilon <= EPSILON_RANGE_BY_TYPE["P"][1]:
        return "P"
    if EPSILON_RANGE_BY_TYPE["PC"][0] <= epsilon <= EPSILON_RANGE_BY_TYPE["PC"][1]:
        return "PC"
    raise ValueError(f"Unsupported pectin epsilon: {epsilon}")


def _epsilon_step_code(epsilon: float) -> str:
    return f"{epsilon_to_step_index(epsilon):02d}"


def _pectin_atomtype_name(chain_index: int, bead_index: int, epsilon: float) -> str:
    bead_type = classify_pectin_epsilon(epsilon)
    return f"{bead_type}e{_epsilon_step_code(epsilon)}c{chain_index}b{bead_index}"


def _draw_pectin_epsilon(rng: random.Random) -> float:
    return step_index_to_epsilon(rng.randint(1, EPSILON_STEP_COUNT))


def assign_all_chain_bead_epsilons(
    chain_count: int,
    beads_per_chain: int,
    rng: random.Random | None = None,
) -> AssignmentMap:
    rng = rng or random.Random()
    assignments: AssignmentMap = {}
    for chain_index in range(1, chain_count + 1):
        chain_assignments: Dict[int, Assignment] = {}
        for bead_index in range(1, beads_per_chain + 1):
            epsilon = _draw_pectin_epsilon(rng)
            chain_assignments[bead_index] = {
                "chain_index": chain_index,
                "bead_index": bead_index,
                "epsilon": epsilon,
                "bead_type": classify_pectin_epsilon(epsilon),
                "atomtype": _pectin_atomtype_name(chain_index, bead_index, epsilon),
            }
        assignments[chain_index] = chain_assignments
    return assignments


def iter_assignments(assignments: AssignmentMap) -> Iterable[Assignment]:
    for chain_index in sorted(assignments):
        for bead_index in sorted(assignments[chain_index]):
            yield assignments[chain_index][bead_index]


def sorted_assignments_by_epsilon(assignments: AssignmentMap) -> List[Assignment]:
    return sorted(
        iter_assignments(assignments),
        key=lambda item: (item["epsilon"], item["chain_index"], item["bead_index"]),
    )


def _base_header() -> str:
    return """;;;;; Sudowoodo Force Field: Particle definition and LJ interactions
;;;;;
;;;;; File generated by build_sweep.py
;;;;;
;;;;; Version: 0.0.1
;;;;;

[ defaults ]
1 2 ; sigma-epsilon format of LJ parameters

"""


def write_per_bead_base_itp(output_path: Path, assignments: AssignmentMap) -> None:
    lines = [_base_header(), "[ atomtypes ]", "; name  at.num  mass  charge  ptype  sigma  epsilon"]
    for name, mass, sigma, epsilon in CORE_ATOMTYPES:
        lines.append(f"{name:<12} 1 {mass:>7.1f} 0.000 A {0.0:>9.6f} {0.0:>11.6f}")

    for assignment in sorted_assignments_by_epsilon(assignments):
        lines.append(
            f"{assignment['atomtype']:<12} 1 {26.6:>7.1f} 0.000 A {0.0:>9.6f} {0.0:>11.6f}"
        )

    lines.extend([
        "",
        "[ nonbond_params ]",
        ";   i     j  func  sigma(nm)   epsilon(kJ/mol)",
    ])
    interaction_rows = _build_nonbond_param_rows(assignments)
    for left, right, func, sigma, epsilon in interaction_rows:
        lines.append(f"{left:>12} {right:>12} {func:>3} {sigma:>12.6f} {epsilon:>12.6f}")

    output_path.write_text("\n".join(lines) + "\n")


def _atomtype_parameters(assignments: AssignmentMap) -> Dict[str, Tuple[float, float]]:
    parameters = {name: (sigma, epsilon) for name, _mass, sigma, epsilon in CORE_ATOMTYPES}
    for assignment in iter_assignments(assignments):
        parameters[str(assignment["atomtype"])] = (PECTIN_SIGMA, float(assignment["epsilon"]))
    return parameters


def _build_nonbond_param_rows(assignments: AssignmentMap) -> List[Tuple[str, str, int, float, float]]:
    parameters = _atomtype_parameters(assignments)
    pectin_atomtypes = [str(assignment["atomtype"]) for assignment in sorted_assignments_by_epsilon(assignments)]
    rows: List[Tuple[str, str, int, float, float]] = list(CORE_NONBOND_PARAMS)

    for left in ("C", "X"):
        for right in pectin_atomtypes:
            left_sigma, left_epsilon = parameters[left]
            right_sigma, right_epsilon = parameters[right]
            sigma = (left_sigma + right_sigma) / 2.0
            epsilon = math.sqrt(left_epsilon * right_epsilon)
            rows.append((left, right, 1, round(sigma, 6), round(epsilon, 6)))

    for index, left in enumerate(pectin_atomtypes):
        for right in pectin_atomtypes[index:]:
            left_sigma, left_epsilon = parameters[left]
            right_sigma, right_epsilon = parameters[right]
            sigma = (left_sigma + right_sigma) / 2.0
            epsilon = math.sqrt(left_epsilon * right_epsilon)
            rows.append((left, right, 1, round(sigma, 6), round(epsilon, 6)))
    return rows


def _replace_pectin_atomtypes(template_text: str, chain_assignments: Dict[int, Assignment]) -> str:
    lines = template_text.splitlines()
    out_lines: List[str] = []
    in_atoms = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[atoms]") or stripped.startswith("[ atoms ]"):
            in_atoms = True
            out_lines.append(line)
            continue
        if in_atoms and stripped.startswith("[") and not (stripped.startswith("[atoms]") or stripped.startswith("[ atoms ]")):
            in_atoms = False
        if in_atoms and stripped and not stripped.startswith(";"):
            parts = line.split()
            bead_index = int(parts[0])
            parts[1] = str(chain_assignments[bead_index]["atomtype"])
            out_lines.append("  " + "    ".join(parts))
            continue
        out_lines.append(line)
    return "\n".join(out_lines) + "\n"


def write_per_bead_pectin_itp(template_path: Path, output_path: Path, assignments: AssignmentMap, chain_index: int = 1) -> None:
    template_text = template_path.read_text()
    output_path.write_text(_replace_pectin_atomtypes(template_text, assignments[chain_index]))


def write_assignment_report(output_path: Path, assignments: AssignmentMap) -> None:
    lines = []
    for assignment in sorted_assignments_by_epsilon(assignments):
        lines.append(
            f"{assignment['atomtype']:<12} 1 26.6 0.000 A 1.000000 {assignment['epsilon']:.6f}"
        )
    output_path.write_text("\n".join(lines) + "\n")


def _count_pectin_beads(pectin_itp_path: Path) -> int:
    bead_count = 0
    in_atoms = False
    for line in pectin_itp_path.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("[atoms]") or stripped.startswith("[ atoms ]"):
            in_atoms = True
            continue
        if in_atoms and stripped.startswith("["):
            break
        if in_atoms and stripped and not stripped.startswith(";"):
            bead_count += 1
    return bead_count


def build_variant(
    output_dir: Path,
    pectin_itp_template: Path,
    chain_count: int = 1,
    rng: random.Random | None = None,
) -> AssignmentMap:
    output_dir.mkdir(parents=True, exist_ok=True)
    bead_count = _count_pectin_beads(pectin_itp_template)
    assignments = assign_all_chain_bead_epsilons(chain_count, bead_count, rng=rng)
    write_per_bead_base_itp(output_dir / "sudowoodo_base.itp", assignments)
    write_per_bead_pectin_itp(pectin_itp_template, output_dir / "sudowoodo_pectin.itp", assignments)
    write_assignment_report(output_dir / "pectin_assignment_report.txt", assignments)
    return assignments


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate per-bead pectin epsilon sweeps in 0.1 increments.")
    parser.add_argument("--out", type=Path, required=True, help="Output directory")
    parser.add_argument(
        "--pectin-itp-template",
        type=Path,
        default=Path("toppar_custom/sudowoodo_pectin.itp"),
        help="Template pectin ITP path",
    )
    parser.add_argument("--chains", type=int, default=1, help="Number of pectin chains to assign")
    parser.add_argument("--seed", type=int, default=None, help="Random seed")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rng = random.Random(args.seed)
    build_variant(args.out, args.pectin_itp_template, chain_count=args.chains, rng=rng)


if __name__ == "__main__":
    main()
